title: Ruthu S Sanketh
author:
  name: ©Ruthu
  email: ruthu.sankethi@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Disclaimer: This website was not made by ChatGPT.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  #social_links:
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ruthu-s-sanketh/" }
  #   - { platform: medium,         user_url: "https://ruthussanketh.medium.com/" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
